server:
  port: 8080

spring:
  datasource:
    username: root
    password: 123456
    #url中database为对应的数据库名称
    url: jdbc:mysql://localhost:3306/java?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.example.demo8.entity

#showSql
logging:
  level:
    com.example.demo8.mapper: debug
debug: true
